x-build:
  &build
  context: ./
  args:
    PHP_VERSION: ${PHP_VERSION-7.0}
    COMPOSER_VERSION: ${COMPOSER_VERSION-2.2}
  dockerfile: docker/Dockerfile

services:
  clean:
    image: registry.xaer.de/xaer/php:${PHP_VERSION-7.0}-cli
    build:
      <<: *build
    volumes:
      - ./:/src
    working_dir: "/src"
    command: [ "sh", "-c", "rm -rf vendor || rm phpunit_results.xml || rm phpstan.json || rm composer.lock || rm .phpunit.result.cache" ]
  setup:
    image: registry.xaer.de/xaer/php:${PHP_VERSION-7.0}-cli
    build:
      <<: *build
    volumes:
      - ./:/src
    working_dir: "/src"
    command: ["sh", "-c", "composer update --with=php:$$(php -r \"echo PHP_VERSION.PHP_EOL;\")"]
  php:
    image: registry.xaer.de/xaer/php:${PHP_VERSION-7.0}-cli
    build:
      <<: *build
    depends_on:
      setup:
        condition: service_completed_successfully
    volumes:
      - ./:/src
    working_dir: "/src"
